### PR TITLE
Add border-radius to textarea element

### PR DESCRIPTION
**Pull request by guptasajal411**
Hi
I noticed that `border-radius` was consistent in Form and Input elements, but it was missing in the `textarea` element. So I added it to eccentric.css file. I set the `border-radius` to 4px, which is the same as of other elements.
Here, you can see the output:

**Before:**
image

**After:**
image

This PR is created for `v2.0` branch.

It'll be great if you can merge this PR!

### CODE REVIEW

**Comment by yashsehgal** [comment]
That's great @guptasajal411 
Thanks for your time, really appreciate it :)

**Review by yashsehgal — APPROVED** [review]
Approving this code change

**Comment by guptasajal411** [comment]
Thanks a lot @yashsehgal. BTW this is my first open-source contribution! 😄

**Comment by yashsehgal** [comment]
> Thanks a lot @yashsehgal. BTW this is my first open-source contribution! 😄

Congrats on that note @guptasajal411 
Have you tried this library??

**Comment by guptasajal411** [comment]
> Congrats on that note @guptasajal411
> Have you tried this library??

I will try using it on my next project, I am learning frontend web development and libraries like eccentrictouch and bootstrap makes the work so easy.
Also, looking forward to more contributions to this library.

**Comment by yashsehgal** [comment]
> > Congrats on that note @guptasajal411
> > Have you tried this library??
> 
> I will try using it on my next project, I am learning frontend web development and libraries like eccentrictouch and bootstrap makes the work so easy.
> Also, looking forward to more contributions to this library.

That's really great! We'll be waiting for your feedback 😺

**Pull request merged**
