### PR TITLE
Added cursor pointer

### LINKED ISSUE #222: Add a pointer cursor on the buttons
**Is your feature request related to a problem? Please describe.**
When the pointer is hovered on the buttons on homepage, pointer should be cursor type.

### PR DESCRIPTION
**Pull request by supzi-del**
Fixes #222

### CODE REVIEW

**Comment by yashsehgal** [comment]
Your code changes are having some conflicts, try pulling the code changes from the branch `v2.0` and then create a new/final commit for this PR. Hope you get me :D

**Review by yashsehgal — COMMENTED** [review]
Hey, @supzi-del Are you making these PRs on GitHub interfaces?

**Comment by yashsehgal** [comment]
Can you join the [discord server](https://discord.gg/GpHBdA68fg)? I will guide you there

**Comment by ayushseth07** [comment]
please assign me this issue.

**Comment by yashsehgal** [comment]
This branch has some conflicts in the `eccentric.css` file. Also, Please update the `eccentric.scss` file using Live SASS Compiler. If you need any sort of help, feel free to ask

**Pull request closed without merging**
